app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return redirect('movie');
});

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
  Route::auth();
  Route::resource('movie', 'MovieController');
  Route::resource('movie.review', 'ReviewController', ['only' => [
      'store', 'update', 'destroy', 'create'
    ]]);
  Route::get('search', 'MovieController@search');
});

app/Movie.php
<?php

namespace App;

use Spatie\SearchIndex\Searchable;
use Illuminate\Database\Eloquent\Model;

class Movie extends Model implements Searchable
{
  public function user () {
    return $this->belongsTo('App\User');
  }

  public function reviews () {
    return $this->hasMany('App\Review');
  }

  /**
   * Returns an array with properties which must be indexed
   *
   * @return array
   */
  public function getSearchableBody()
  {
    $searchableProperties = [
      'title' => $this->title,
    ];

    return $searchableProperties;

  }

  /**
   * Return the type of the searchable subject
   *
   * @return string
   */
  public function getSearchableType()
  {
    return 'movie';
  }

  /**
   * Return the id of the searchable subject
   *
   * @return string
   */
  public function getSearchableId()
  {
    return $this->id;
  }
}

app/Http/Controllers/MovieController.php
<?php

namespace App\Http\Controllers;

use SearchIndex;
use File;
use Image;
use Gate;
use App\Movie;
use Illuminate\Http\Request;

use App\Http\Requests;

class MovieController extends Controller
{
  /**
   * Holds the validation array for storing and updating
   *
   * @var array $rules
   */
  private $rules = [
    'title' => 'required|min:6',
    'description' => 'required|min:6',
    'movie_length' => 'required',
    'director' => 'required',
    'rating' => 'required',
  ];

  /**
   * Create a new controller instance.
   *
   * @return void
   */
  public function __construct()
  {
      $this->middleware('auth', [
        'except' => ['index' ,'show', 'search']
      ]);
  }

  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    $movies = Movie::orderBy('created_at', 'desc')->get();

    return view('movie.index', [
      'movies' => $movies,
    ]);
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    return view('movie.create');
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    $this->validate($request, $this->rules);

    $imageName = 'missing.jpg';
    if ($request->hasFile('image')) {
      $imageName = $this->storeImage($request->file('image'));
    }

    $movie = new Movie;
    $movie->title = $request->title;
    $movie->description = $request->description;
    $movie->movie_length = $request->movie_length;
    $movie->director = $request->director;
    $movie->rating = $request->rating;
    $movie->image = $imageName;
    $movie->user_id = $request->user()->id;
    $movie->save();

    SearchIndex::upsertToIndex($movie);

    return redirect()->route('movie.show', [$movie])
                     ->with('notice', 'Movie Created');
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function show($id)
  {
    $movie = Movie::find($id);

    return view('movie.show', [
      'movie' => $movie,
    ]);
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit($id)
  {
    $movie = Movie::find($id);

    if (Gate::denies('modify', $movie)) {
      abort(403);
    }

    return view('movie.edit', [
      'movie' => $movie,
    ]);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, $id)
  {
    $movie = Movie::find($id);

    if (Gate::denies('modify', $movie)) {
      abort(403);
    }

    $this->validate($request, $this->rules);

    if ($request->hasFile('image')) {
      $imageName = $this->storeImage($request->file('image'));
      if ($movie->image != 'missing.jpg') File::delete(public_path('uploads/movies/img/') . $movie->image);
      $movie->image = $imageName;
    }

    $movie->title = $request->title;
    $movie->description = $request->description;
    $movie->movie_length = $request->movie_length;
    $movie->director = $request->director;
    $movie->rating = $request->rating;
    $movie->save();

    SearchIndex::upsertToIndex($movie);

    return redirect()->route('movie.show', [$movie])
                     ->with('notice', 'Movie Updated');
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy($id)
  {
    $movie = Movie::find($id);

    if (Gate::denies('modify', $movie)) {
      abort(403);
    }

    if ($movie->image != 'missing.jpg') File::delete(public_path('uploads/movies/img/') . $movie->image);
    $movie->delete();

    return redirect('movie');
  }

  private function storeImage ($image) {
    $imageName = md5($image->getClientOriginalName() . microtime())
                  . '.' . $image->getClientOriginalExtension();

    Image::make($image)
            ->resize(800, null, function ($constraint) {
              $constraint->aspectRatio();
            })
            ->save(public_path('uploads/movies/img/') . $imageName);

    return $imageName;
  }

  public function search (Request $request) {
    $query = [
      'index' => 'moviereview',
      'body' => [
        'query' => [
          'match_phrase' => [
            'title' => $request->q
          ]
        ]
      ]
    ];

    $result = SearchIndex::getResults($query);

    $movies = null;
    foreach ($result['hits']['hits'] as $movie) {
      $movies[] = Movie::find($movie['_id']);
    }

    return view('movie.index', [
      'movies' => $movies,
    ]);
  }
  
}

resources/views/movie/create.blade.php
@extends('layouts.app')

@section('content')

  @include('common.errors')

  <form action="{{ route('movie.store') }}"
        method="POST"
        enctype="multipart/form-data">

    {{ csrf_field() }}

    <label for="title">Title</label>
    <input type="text"
            name="title"
            id="title"
            value="{{ old('title') }}">

    <br>
    <label for="description">Description</label>
    <textarea type="text"
            name="description"
            id="description">{{ old('description') }}</textarea>

    <br>
    <label for="movie_length">Movie Length</label>
    <input type="text"
            name="movie_length"
            id="movie_length"
            value="{{ old('movie_length') }}">

    <br>
    <label for="director">Director</label>
    <input type="text"
            name="director"
            id="director"
            value="{{ old('director') }}">

    <br>
    <label for="rating">Rating</label>
    <input type="text"
            name="rating"
            id="rating"
            value="{{ old('rating') }}">

    <br>
    <label for="image">Image</label>
    <input type="file"
            name="image"
            id="image"
            accept="image/*">

    <br>
    <button type="submit">Submit</button>

  </form>

@endsection

resources/views/movie/edit.blade.php
@extends('layouts.app')

@section('content')

  @include('common.errors')

  <form action="{{ route('movie.update', [$movie]) }}"
        method="POST"
        enctype="multipart/form-data">

    {{ csrf_field() }}
    {{ method_field('PUT') }}

    <label for="title">Title</label>
    <input type="text"
            name="title"
            id="title"
            value="{{ $movie->title }}">

    <br>
    <label for="description">Description</label>
    <textarea type="text"
            name="description"
            id="description">{{ $movie->description }}</textarea>

    <br>
    <label for="movie_length">Movie Length</label>
    <input type="text"
            name="movie_length"
            id="movie_length"
            value="{{ $movie->movie_length }}">

    <br>
    <label for="director">Director</label>
    <input type="text"
            name="director"
            id="director"
            value="{{ $movie->director }}">

    <br>
    <label for="rating">Rating</label>
    <input type="text"
            name="rating"
            id="rating"
            value="{{ $movie->rating }}">

    <br>
    <label for="image">Image</label>
    <input type="file"
            name="image"
            id="image"
            accept="image/*">

    <br>
    <button type="submit">Submit</button>

  </form>

@endsection

resources/views/movie/index.blade.php
@extends('layouts.app')

@section('content')

  @if (Auth::guest())
    <div class="jumbotron">
      <h1>Your Favorite Movies Reviewed</h1>
      <p>Disrupt occupy bespoke raw denim. Organic direct trade synth, four dollar toast vegan pitchfork lo-fi yuccie hammock green juice. Hoodie leggings selvage YOLO, offal cronut disrupt typewriter. </p>
      <p><a href="{{ url('register') }}" class="btn btn-primary btn-lg">Sign Up To Write A Review</a></p>
    </div>
  @endif

  @if ($movies)
    <div class="row">
      @foreach ($movies as $movie)

        <div class="col-sm-6 col-md-3">
          <div class="thumbnail">
            <a href="{{ route('movie.show', [$movie]) }}" class="image">
              <img src="{{ url('imagecache/poster/' . $movie->image) }}">
            </a>
          </div>
        </div>

      @endforeach
    </div>
  @endif

@endsection

resources/views/movie/show.blade.php
@extends('layouts.app')

@section('content')

  <div class="panel panel-default" id="show_page">
    <div class="panel-body">
      <div class="row">
        <div class="col-md-4">
          <div class="text-center">
            <img src="{{ url('imagecache/poster/'. $movie->image) }}">
            <div class="star-rating" data-score="{{ $movie->reviews->avg('rating') }}"></div>
            <em>{{ count($movie->reviews) }} reviews</em>
          </div>
          <div class="table-responsive">
            <table class="table">
              <tbody>
                <tr>
                  <td><strong>Title</strong></td>
                  <td>{{ $movie->title }}</td>
                </tr>
                <tr>
                  <td><strong>Description</strong></td>
                  <td>{{ $movie->description }}</td>
                </tr>
                <tr>
                  <td><strong>Movie length</strong></td>
                  <td>{{ $movie->movie_length }}</td>
                </tr>
                <tr>
                  <td><strong>Director</strong></td>
                  <td>{{ $movie->director }}</td>
                </tr>
                <tr>
                  <td><strong>Rating</strong></td>
                  <td>{{ $movie->rating }}</td>
                </tr>
              </tbody>
            </table>
          </div>
          <a href="{{ route('movie.review.create', [$movie]) }}">Write a Review</a>
        </div>
        <div class="col-md-7 col-md-offset-1">
          <h1 class="review_title">{{ $movie->title }}</h1>
          <p>{{ $movie->description }}</p>

          @if (count($movie->reviews) > 0)

            @foreach ($movie->reviews()->orderBy('created_at', 'desc')->get() as $review)
              <div class="reviews">
                <div class="star-rating" data-score="{{ $review->rating }}"></div>
                <p>{{ $review->comment }}</p>
              </div>
            @endforeach

          @else

            <h3>No reviews just yet, would you like to add the first!</h3>
            <a href="{{ route('movie.review.create', [$movie]) }}" class="btn btn-danger">Write Review</a>

          @endif
        </div>
      </div>
    </div>
  </div>

  @can ('modify', $movie)
    <a href="{{ route('movie.edit', [$movie]) }}">Edit</a>
    <form action="{{ route('movie.destroy', [$movie]) }}"
          method="POST">
      {{ csrf_field() }}
      {{ method_field('DELETE') }}
      <button type="submit">Delete</button>
    </form>
  @endcan

  <script>
    $('.star-rating').raty({
      path: '{{ url("includes/raty-master/images/") }}',
      readOnly: true,
      score: function () {
        return $(this).attr('data-score');
      }
    });
  </script>

@endsection