app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return redirect('movie');
});

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
  Route::auth();
  Route::resource('movie', 'MovieController');
  Route::resource('movie.review', 'ReviewController', ['only' => [
      'store', 'update', 'destroy', 'create'
    ]]);
  Route::get('search', 'MovieController@search');
});

app/Http/Controllers/ReviewController.php
<?php

namespace App\Http\Controllers;

use App\Movie;
use App\Review;
use Illuminate\Http\Request;

use App\Http\Requests;

class ReviewController extends Controller
{
  /**
   * Holds the validation array for storing and updating
   *
   * @var array $rules
   */
  private $rules = [
    'rating' => 'required',
    'comment' => 'required',
  ];

  /**
   * Create a new controller instance.
   *
   * @return void
   */
  public function __construct()
  {
      $this->middleware('auth', [
        'except' => ['index' ,'show']
      ]);
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create(Movie $movie)
  {
    return view('review.create', [
      'movie' => $movie,
    ]);
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request, Movie $movie)
  {
    $this->validate($request, $this->rules);

    $review = new Review;
    $review->rating = $request->rating;
    $review->comment = $request->comment;
    $review->movie_id = $movie->id;
    $review->save();

    return redirect()->route('movie.show', [$movie]);
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit(Movie $movie, $id)
  {
    $review = Review::find($id);

    return view('movie.review.edit', [
      'movie' => $movie,
      'review' => $review,
    ]);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, Movie $movie, $id)
  {
    $this->validate($request, $rules);

    $review = Review::find($id);

    $review->rating = $request->rating;
    $review->comment = $request->comment;
    $revie->save();

    return redirect()->route('movie.show', [$movie]);
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy(Movie $movie, $id)
  {
    $review = Review::find($id);

    $review->delete();

    return redirect('movie.show', [$movie]);
  }
}

resources/views/review/create.blade.php
@extends('layouts.app')

@section('content')

  <h1>New Review</h1>

  @include('common.errors')

  <form action="{{ route('movie.review.store', [$movie]) }}"
        method="POST">

    {{ csrf_field() }}

    <div class="star-rating"></div>

    <br>

    <label for="comment">Comment</label>
    <textarea type="text"
           name="comment"
           id="comment">{{ old('comment') }}</textarea>

    <br>

    <button type="submit">Submit</button>

  </form>

  <script>
    $('.star-rating').raty({
      path: '{{ url("includes/raty-master/images/") }}',
      scoreName: 'rating'
    });
  </script>

@endsection

resources/views/review/edit.blade.php
@extends('layouts.app')

@section('content')

  <h1>New Review</h1>

  @include('common.errors')

  <form action="{{ route('movie.review.update', [$movie, $review]) }}"
        method="POST">

    {{ csrf_field() }}
    {{ method_field('PUT') }}

    <label for="rating">Rating</label>
    <input type="text"
           name="rating"
           id="rating"
           value="{{ $review->rating }}">

    <br>

    <label for="comment">Comment</label>
    <textarea type="text"
           name="comment"
           id="comment">{{ $review->comment }}</textarea>

    <br>

    <button type="submit">Submit</button>

  </form>

@endsection